name: Release

on:
  push:
    branches: [ main ]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npx ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          PREV_MODULE_VERSION=$(git describe --tags --always)
          echo $PREV_MODULE_VERSION
          git branch
          npx semantic-release --tag-format "\${version}" --branches "main" --plugins "@semantic-release/commit-analyzer" "@semantic-release/release-notes-generator" "@semantic-release/github"
          CURRENT_MODULE_VERSION=$(git describe --tags --always)
          echo "$PREV_MODULE_VERSION vs $CURRENT_MODULE_VERSION"
#          if [[ ${{ PREV_MODULE_VERSION != CURRENT_MODULE_VERSION }} ]]; then
#            echo "Publish started..."
#            npm --no-git-tag-version version $MODULE_VERSION
#            npm publish --access public
#          else
#              echo "There is no need to publish the package, skipping"
#          fi

